//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orange.EPilot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Orange_EPilot {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Orange_EPilot() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orange.EPilot.Resources.Orange.EPilot", typeof(Orange_EPilot).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter.
        /// </summary>
        internal static string Button_Export_Text {
            get {
                return ResourceManager.GetString("Button_Export_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats (GoogleAnalytics, MS App Insight).
        /// </summary>
        internal static string CustomAction_AnalyticsDesciption {
            get {
                return ResourceManager.GetString("CustomAction_AnalyticsDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiques.
        /// </summary>
        internal static string CustomAction_AnalyticsTitle {
            get {
                return ResourceManager.GetString("CustomAction_AnalyticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres généraux de l&apos;application.
        /// </summary>
        internal static string CustomAction_DataBaseConfigDescription {
            get {
                return ResourceManager.GetString("CustomAction_DataBaseConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres généraux.
        /// </summary>
        internal static string CustomAction_DataBaseConfigTitle {
            get {
                return ResourceManager.GetString("CustomAction_DataBaseConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permet d&apos;exporter les données dans une feuille Excel..
        /// </summary>
        internal static string CustomAction_ExportExcelDescription {
            get {
                return ResourceManager.GetString("CustomAction_ExportExcelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter les données.
        /// </summary>
        internal static string CustomAction_ExportExcelTitle {
            get {
                return ResourceManager.GetString("CustomAction_ExportExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu tuile (couleur, ordre).
        /// </summary>
        internal static string CustomAction_SiteConfigDesciption {
            get {
                return ResourceManager.GetString("CustomAction_SiteConfigDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu tuile (couleur, ordre).
        /// </summary>
        internal static string CustomAction_SiteConfigTitle {
            get {
                return ResourceManager.GetString("CustomAction_SiteConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission du site.
        /// </summary>
        internal static string CustomAction_SitePermissionDesciption {
            get {
                return ResourceManager.GetString("CustomAction_SitePermissionDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission du site.
        /// </summary>
        internal static string CustomAction_SitePermissionTitle {
            get {
                return ResourceManager.GetString("CustomAction_SitePermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission d&apos;un utilisateur.
        /// </summary>
        internal static string CustomAction_UserPermissionDesciption {
            get {
                return ResourceManager.GetString("CustomAction_UserPermissionDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission d&apos;un utilisateur.
        /// </summary>
        internal static string CustomAction_UserPermissionTitle {
            get {
                return ResourceManager.GetString("CustomAction_UserPermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre et icone du site.
        /// </summary>
        internal static string CustomAction_WebConfigDesciption {
            get {
                return ResourceManager.GetString("CustomAction_WebConfigDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre, icone.
        /// </summary>
        internal static string CustomAction_WebConfigTitle {
            get {
                return ResourceManager.GetString("CustomAction_WebConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Site collection.
        /// </summary>
        internal static string CustomActionGroup_SiteFunctionnalGroupDescription {
            get {
                return ResourceManager.GetString("CustomActionGroup_SiteFunctionnalGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Site collection.
        /// </summary>
        internal static string CustomActionGroup_SiteFunctionnalGroupTitle {
            get {
                return ResourceManager.GetString("CustomActionGroup_SiteFunctionnalGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Module.
        /// </summary>
        internal static string CustomActionGroup_WebFunctionnalGroupDescription {
            get {
                return ResourceManager.GetString("CustomActionGroup_WebFunctionnalGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Module.
        /// </summary>
        internal static string CustomActionGroup_WebFunctionnalGroupTitle {
            get {
                return ResourceManager.GetString("CustomActionGroup_WebFunctionnalGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation des pages d&apos;administration - Site Scope.
        /// </summary>
        internal static string Feature_Site_AdministrationDescription {
            get {
                return ResourceManager.GetString("Feature_Site_AdministrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Administration - Site Scope.
        /// </summary>
        internal static string Feature_Site_AdministrationTitle {
            get {
                return ResourceManager.GetString("Feature_Site_AdministrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajoute les types de contenu EPilot sur le site.
        /// </summary>
        internal static string Feature_Site_ContentTypesDescription {
            get {
                return ResourceManager.GetString("Feature_Site_ContentTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Contenttypes- Site Scope.
        /// </summary>
        internal static string Feature_Site_ContentTypesTitle {
            get {
                return ResourceManager.GetString("Feature_Site_ContentTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation du menu de navigation spécifiques pour les rubriques - Site Scope.
        /// </summary>
        internal static string Feature_Site_GlobalNavigationDescription {
            get {
                return ResourceManager.GetString("Feature_Site_GlobalNavigationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Menu de navigation rubriques  - Site Scope.
        /// </summary>
        internal static string Feature_Site_GlobalNavigationTitle {
            get {
                return ResourceManager.GetString("Feature_Site_GlobalNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déploiement de la page maitre et des fichiers de design (CSS, JS, ...) - Site Scope.
        /// </summary>
        internal static string Feature_Site_Portal_BrandingDescription {
            get {
                return ResourceManager.GetString("Feature_Site_Portal_BrandingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Design - Site Scope.
        /// </summary>
        internal static string Feature_Site_Portal_BrandingTitle {
            get {
                return ResourceManager.GetString("Feature_Site_Portal_BrandingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebParts globales EPilot.
        /// </summary>
        internal static string Feature_Site_WebPartsDescription {
            get {
                return ResourceManager.GetString("Feature_Site_WebPartsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - WebParts - Site Scope.
        /// </summary>
        internal static string Feature_Site_WebPartsTitle {
            get {
                return ResourceManager.GetString("Feature_Site_WebPartsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation des pages d&apos;administration - Web Scope.
        /// </summary>
        internal static string Feature_Web_AdministrationDescription {
            get {
                return ResourceManager.GetString("Feature_Web_AdministrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Administration - Web Scope.
        /// </summary>
        internal static string Feature_Web_AdministrationTitle {
            get {
                return ResourceManager.GetString("Feature_Web_AdministrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permet de mettre à disposition une fonctionnalité d&apos;export des données vers Excel..
        /// </summary>
        internal static string Feature_Web_ExportExcelDescription {
            get {
                return ResourceManager.GetString("Feature_Web_ExportExcelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Fonctionnalité d&apos;export des données vers Excel.
        /// </summary>
        internal static string Feature_Web_ExportExcelTitle {
            get {
                return ResourceManager.GetString("Feature_Web_ExportExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation de la liste d&apos;actualité.
        /// </summary>
        internal static string Feature_Web_NewsDescription {
            get {
                return ResourceManager.GetString("Feature_Web_NewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Actualités.
        /// </summary>
        internal static string Feature_Web_NewsTitle {
            get {
                return ResourceManager.GetString("Feature_Web_NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajoute la fonctionnalité de gestion des Onglets - Web Scope.
        /// </summary>
        internal static string Feature_Web_OngletDescription {
            get {
                return ResourceManager.GetString("Feature_Web_OngletDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPilot - Onglets - Web Scope.
        /// </summary>
        internal static string Feature_Web_OngletTitle {
            get {
                return ResourceManager.GetString("Feature_Web_OngletTitle", resourceCulture);
            }
        }
    }
}
