//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orange.EPilot.WebParts.Iframe_SSRS {
    
    
    public partial class Iframe_SSRSUserControl {
    }
}
